version: "3.7"

services:

    nextcloud-database:
        image: "mariadb:latest"
        
        volumes:
            - "nc-mariadb:/var/lib/mysql"

        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_RANDOM_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD

        restart: "on-failure"
        networks: ["common"]

    nextcloud-frontend:
        image: "nextcloud:24"

        volumes: 
          - "nc-data:/var/www/html"

        environment:
            # - LETSENCRYPT_HOST
            # - VIRTUAL_HOST
            - TRUSTED_PROXIES
            - OVERWRITEPROTOCOL
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - SMTP_HOST
            - SMTP_PORT
            - SMTP_NAME
            - SMTP_PASSWORD
            - MAIL_FROM_ADDRESS
            - NEXTCLOUD_TRUSTED_DOMAINS
            - NEXTCLOUD_ADMIN_USER
            - NEXTCLOUD_ADMIN_PASSWORD

        depends_on:
            - "nextcloud-database"
        networks: ["nc-net", "common"]

volumes:
    nc-mariadb:
        external: true
    nc-data:
        external: true

networks:
    nc-net:
        external: true
    common:
        internal: true